# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------


from .. import try_manual


# EXAMPLE: /Table/delete/TableOperationDelete
@try_manual
def step_table_delete(test, checks=None):
    if checks is None:
        checks = []
    test.cmd('az storage table delete -y '
             '--account-name "sto328" '
             '--resource-group "{rg}" '
             '--name "{myTable}"',
             checks=checks)
